name: worker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint (basic import check)
        run: |
          poetry run python -c "import wp_python; print('import ok, version=', wp_python.__version__)"

      - name: Run tests
        env:
          # 提供最小环境，单元测试不会访问远端服务
          WP_BASE_URL: https://example.com
        run: |
          poetry run python -m pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build example prod image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: examples/deploy/Dockerfile
          push: false
          tags: wp-python-fastapi:ci
